---
name: vscode-unity-debug
description: Debug adapter for Unity
homepage: https://github.com/Unity-Technologies/vscode-unity-debug
licenses:
  - MIT
languages:
  - CSHARP
categories:
  - DAP

source:
  id: pkg:github/Unity-Technologies/vscode-unity-debug@2.7.2
  asset:
    file: unity-debug-{{ version | strip_prefix "v" }}.vsix

bin:
  vscode-unity-debug: extension/bin/UnityDebug.exe
